name: Release
run-name: Release

on:
  push:
    tags:
      - 'v[0-9]+'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout source'
      - run: |
            git fetch --prune --tags -f
            git tag

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install
        run: npm i
        
      - name: Run
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          QUEUE_ID: ${{ secrets.QUEUE_ID }}
          QUEUE_NAME: ${{ secrets.QUEUE_NAME }}
        run: npm run release